name: flutter_plate
description: Flutter Starter Kit with Bloc pattern
authors:
 - Md Shahab Uddin <tausiq19@gmail.com>
homepage: https://github.com/tausiq/flutter_plate
maintainer: Md Shahab Uddin (tausiq)

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.4.0+140

environment:
  sdk: '>=2.0.0 <3.0.0'
  flutter: 1.17.1

dependencies:
  analyzer: 0.39.4
  bottom_navy_bar: 5.3.2
  cached_network_image: 2.2.0+1
  connection_status_bar: 1.1.2
  cloud_firestore: 0.13.4+2
  dio: 3.0.9
  easy_localization: 2.0.0+1
  equatable: 1.1.0
  fluro: 1.6.3
  firebase_auth: 0.15.5+3
  flutter_bloc: 4.0.0 # depends on bloc (meta), provider
  flutter_localizations:
      sdk: flutter
  flutter_secure_storage: 3.3.1+1
  flutter_stetho: 0.5.2
  font_awesome_flutter: 8.7.0
  google_sign_in: 4.1.1
  http: 0.12.0+4
  json_annotation: 3.0.1
  logger: 0.8.3
  path_provider: 1.6.5
  preferences: 5.1.0 # depends on shared_preferences
  pull_to_refresh: 1.5.7
  rxdart: 0.24.1
  sentry: 3.0.1
  settings_ui: 0.2.0
  smooth_star_rating: 1.0.4+2
  sprintf: 4.0.2
  sqflite: 1.2.1
  wave: 0.0.8

  # The following adds the Cupertino Icons font to your application.
  # Use with the Cupertino Icons class for iOS style icons.
  # cupertino_icons: 0.1.2

dev_dependencies:
  flutter_test:
   sdk: flutter
  flutter_driver:
    sdk: flutter
  floor_generator: 0.11.0
  build_runner: 1.7.4
  json_serializable: 3.2.5
  test: 1.14.3
  bloc_test: 5.1.0
  flutter_native_splash: 0.1.9

flutter_native_splash:
    image: images/logo.png
    color: "2196f3"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font isSupported
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - langs/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato/Lato-Bold.ttf
        - asset: fonts/Lato/Lato-BoldItalic.ttf
          style: italic
        - asset: fonts/Lato/Lato-Black.ttf
          weight: 700
    - family: Cabin
      fonts:
       - asset: fonts/Cabin/Cabin-Regular.ttf
       - asset: fonts/Cabin/Cabin-RegularItalic.ttf
         style: italic
       - asset: fonts/Cabin/Cabin-Bold.ttf
         weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
