name: flutter_plate
description: Flutter Starter Kit with Bloc pattern
authors:
 - Md Shahab Uddin <tausiq19@gmail.com>
homepage: https://github.com/tausiq/flutter_plate
maintainer: Md Shahab Uddin (tausiq)

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.4.1+141

environment:
  sdk: '>=2.6.0 <3.0.0'
  flutter: '>=1.20.0 <1.23.0'

dependencies:
  analyzer: 0.40.6
  bottom_navy_bar: 5.6.0
  cached_network_image: 2.5.0
  cloud_firestore: 0.16.0
  connection_status_bar: 1.1.4
  dartz: 0.9.2
  dio: 3.0.10
  easy_localization: 2.3.3
  equatable: 1.2.5
  firebase_auth: 0.20.0+1
  fluro: 1.7.8
  flutter_bloc: 6.1.1 # depends on bloc (meta), provider
  flutter_localizations:
      sdk: flutter
  flutter_secure_storage: 3.3.5
  font_awesome_flutter: 8.11.0
  get_it: 5.0.4
  google_sign_in: 4.5.9
  http: 0.12.2
  json_annotation: 3.1.1
  logger: 0.9.4
  path_provider: 1.6.27
  preferences: 5.2.1 # depends on shared_preferences
  pull_to_refresh: 1.6.3
  rxdart: 0.25.0
  sentry: 3.0.1
  settings_ui: 0.5.0
  smooth_star_rating: 1.1.1
  sprintf: 5.0.0
  sqflite: 1.3.2+2
  wave: 0.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the Cupertino Icons class for iOS style icons.
  # cupertino_icons: 0.1.2

dev_dependencies:
  bloc_test: 7.1.0
  build_runner: 1.10.13
  floor_generator: 0.18.0
  flutter_driver:
      sdk: flutter
  flutter_native_splash: 0.2.6
  flutter_test:
   sdk: flutter
  json_serializable: 3.5.1
  test: 1.16.0-nullsafety.5

flutter_native_splash:
    image: images/logo.png
    color: "2196f3"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font isSupported
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - langs/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cabin
      fonts:
        - asset: fonts/Cabin/Cabin-Medium.ttf
        - asset: fonts/Cabin/Cabin-MediumItalic.ttf
        - asset: fonts/Cabin/Cabin-Bold.ttf
    - family: icomoon
      fonts:
          - asset: fonts/IcoMoon.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
